window.apnExeFile = {
  CTXT: { layoutID: 1 },
  property: {
    ver: "1.0",
    denyCloneLocal: true,
    allowClearTimeout: true,
    denyWidgetStartEvent: true,
    denyInvisibleIntersect: true,
    fixBookStartProcess: true,
    allowImmediateContentLoad: true,
    fixBookPageLayout: true,
    fixOveralyRun: true,
    fix2SideBookCase1: true,
    fixWgtPut: true,
    fixScreenPadding: true,
    corpID: "",
    accountID: "",
    title: "실수 TEST (Mo)",
    categoryId: "",
    type: "P",
    id: "2a31d90d13724c47ac2179920c8bac4f",
    createDate: "20240709152330",
  },
  pages: {
    1: {
      UI: { title: "Page 1", order: 1 },
      objects: {
        "3836265A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101313227,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$main" },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            layers: {
              1: { title: "home", id: "3836266A1_" },
              3: { title: "q1", id: "3836445A1_" },
              4: { title: "q1-2", id: "3836634A1_" },
              5: { title: "q1-3", id: "3836814A1_" },
              6: { title: "q1-4", id: "3836972A1_" },
              7: { title: "q2", id: "3837102A1_" },
              8: { title: "q2(same)", id: "3837224A1_" },
              9: { title: "q2-2", id: "3837372A1_" },
              10: { title: "q2-3", id: "3837556A1_" },
              11: { title: "q3", id: "3837722A1_" },
              12: { title: "q3-2", id: "3837882A1_" },
              13: { title: "q3-3", id: "3838004A1_" },
              14: { title: "ending", id: "3838269A1_" },
            },
            layerIndex: 14,
            children: [
              "3836266A1_",
              "3836445A1_",
              "3836634A1_",
              "3836814A1_",
              "3836972A1_",
              "3837102A1_",
              "3837224A1_",
              "3837372A1_",
              "3837556A1_",
              "3837722A1_",
              "3837882A1_",
              "3838004A1_",
              "3838269A1_",
            ],
          },
        },
        "3836266A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313228 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "3836292A1_",
              "3836293A1_",
              "3836377A1_",
              "3836388A1_",
              "3836389A1_",
              "3836391A1_",
              "3836392A1_",
            ],
          },
        },
        "3836292A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313230,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI47e03a77a4e9401bb45b305bab85aee3_png",
                C: 0,
                A: "transparent",
                a: false,
                j: "pointer",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 614 },
            shape: { type: 1, w: 320, h: 60 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "3" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|25",
              order: 1,
            },
          ],
        },
        "3836293A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313231,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIc0ae7b5e4edf494794ac08437ad0f7ff_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 8, y: 212 },
            shape: { type: 1, w: 343.1256830601093, h: 167 },
            cx: 0,
            cy: 0,
          },
        },
        "3836377A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313234,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI7295f1d8779d4e86b21bbe3275a80273_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_1",
              },
            },
          },
          init: {
            position: { x: 460, y: 110 },
            shape: { type: 1, w: 198, h: 177 },
            cx: 0,
            cy: 0,
          },
        },
        "3836388A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313235,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI797d0abc77a74e73bee12e917269a91e_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_5",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 468, y: 674 },
            shape: { type: 1, w: 203, h: 197 },
            cx: 0,
            cy: 0,
          },
        },
        "3836389A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313236,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIdddc4a24a0e1487b906902f96ec0fa8c_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1354, y: 175 },
            shape: { type: 1, w: 174, h: 172 },
            cx: 0,
            cy: 0,
          },
        },
        "3836391A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313237,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI82317bb9ef8d4806aab4db4324eeb797_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_3",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1487, y: 368 },
            shape: { type: 1, w: 192, h: 264 },
            cx: 0,
            cy: 0,
          },
        },
        "3836392A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313238,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI430661f0b44e4d078ead931d2e6245fd_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_4",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1237, y: 730 },
            shape: { type: 1, w: 190, h: 154 },
            cx: 0,
            cy: 0,
          },
        },
        "3836445A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313239 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3836461A1_", "3836496A1_", "3836514A1_", "3836515A1_"],
          },
        },
        "3836461A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313241,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "음식점에서 주문한 음식과\n다른 음식이 나왔다면?",
                L: "#FFFFFF",
                K: "16px",
              },
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3836496A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313243,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3836514A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313248,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIf047ae4968c34d478241c9ba9134fefb_png",
                O: true,
                T: 0,
                Q: "바로 직원을 부른다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1_명료,적극",
              },
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "4" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|50",
              order: 1,
            },
          ],
        },
        "3836515A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313249,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI8f8e71bc21d1417fb90826a00a7c20e8_png",
                O: true,
                T: 0,
                Q: "주문서를 다시 확인해본다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1_유연,신중,온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "7" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|50",
              order: 1,
            },
          ],
        },
        "3836634A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313251 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3840971A1_", "3840972A1_", "3840973A1_", "3840974A1_"],
          },
        },
        "3836814A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313257 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3841019A1_", "3841020A1_", "3841021A1_", "3841022A1_"],
          },
        },
        "3836972A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313263 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3841067A1_", "3841068A1_", "3841069A1_", "3841070A1_"],
          },
        },
        "3837102A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313269 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3841301A1_", "3841302A1_", "3841303A1_", "3841304A1_"],
          },
        },
        "3837224A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313275 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3841416A1_", "3841417A1_", "3841418A1_", "3841419A1_"],
          },
        },
        "3837372A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313281 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "3841804A1_",
              "3841805A1_",
              "3841806A1_",
              "3841807A1_",
              "3841808A1_",
            ],
          },
        },
        "3837556A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313287 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3841922A1_", "3841923A1_", "3841924A1_", "3841925A1_"],
          },
        },
        "3837722A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313293 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3842067A1_", "3842068A1_", "3842069A1_", "3842070A1_"],
          },
        },
        "3837882A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313299 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3842234A1_", "3842235A1_", "3842236A1_", "3842237A1_"],
          },
        },
        "3838004A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313305 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3842343A1_", "3842344A1_", "3842345A1_", "3842346A1_"],
          },
        },
        "3838269A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330050 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3843145A1_", "3842680A1_", "3843484A1_"] },
        },
        "3840227A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 99999967,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI5eaf32351ee54abf921873756c717d36_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
        },
        "3840971A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330121,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "만약 업무 중에 실수로 \n중요한 문서를 삭제했다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3840972A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330122,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3840973A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330123,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIf047ae4968c34d478241c9ba9134fefb_png",
                O: true,
                T: 0,
                Q: "백업된 파일이 있는지 \n바로 찾아본다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1-2_명료",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "5" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|75",
              order: 1,
            },
          ],
        },
        "3840974A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330124,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI8f8e71bc21d1417fb90826a00a7c20e8_png",
                O: true,
                T: 0,
                Q: "일단 충격받고 도움을 청한다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1-2_적극",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "5" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|75",
              order: 1,
            },
          ],
        },
        "3841019A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330125,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "내가 중요한 팀플에서 늦었다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3841020A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330126,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3841021A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330127,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIf047ae4968c34d478241c9ba9134fefb_png",
                O: true,
                T: 0,
                Q: "왜 늦었는지 설명한다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1-3_명료",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "6" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3841022A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330128,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI8f8e71bc21d1417fb90826a00a7c20e8_png",
                O: true,
                T: 0,
                Q: "미안해ㅜㅜㅜ잘못했어ㅜㅜ흑흐규ㅠㅡㅠ",
                j: "pointer",
                K: "14px",
                k: "btn$q1-3_적극",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "6" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3841067A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330129,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "교수님께 이메일을 잘못 보냈다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3841068A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330130,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3841069A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330131,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIf047ae4968c34d478241c9ba9134fefb_png",
                O: true,
                T: 0,
                Q: "처음부터 잘못보낼 일이 \n없다고 생각한다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1-4_명료",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3841070A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330132,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI8f8e71bc21d1417fb90826a00a7c20e8_png",
                O: true,
                T: 0,
                Q: "빠르게 이메일을 즉시 회수한 후\n오해를 방지하기 위해 다시 문자를 보낸다.",
                j: "pointer",
                K: "14px",
                k: "btn$q1-4_적극",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3841301A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330133,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "정말 착한 후배인데 실수를 많이 한다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3841302A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330134,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3841303A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330135,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI47f0ed087ae64e6f9df147118fc23a62_png",
                O: true,
                T: 0,
                Q: "자꾸 실수하는데 착한 건 중요한 게 아니지",
                j: "pointer",
                K: "14px",
                k: "btn$q2_유연",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "9" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|75",
              order: 1,
            },
          ],
        },
        "3841304A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330136,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIbee8e37796d1425c85d9e05d56edf430_png",
                O: true,
                T: 0,
                Q: "실수는 하지만 평소에 착하니까 넘어가자",
                j: "pointer",
                K: "14px",
                k: "btn$q2_신중,온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "11" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|60",
              order: 1,
            },
          ],
        },
        "3841416A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330138,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "정말 착한 후배인데 실수를 많이 한다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3841417A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330139,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3841418A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330140,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIe26fdc0bb331437cb6aa435b844223a7_png",
                O: true,
                T: 0,
                Q: "자꾸 실수하는데 착한 건 중요한 게 아니지",
                j: "pointer",
                K: "14px",
                k: "btn$q1_명료,적극_5",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "4" },
              transit: {},
              order: 0,
            },
          ],
        },
        "3841419A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330141,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI7af982f232e24a52a94f31efec5ec40a_png",
                O: true,
                T: 0,
                Q: "실수는 하지만 평소에 착하니까 넘어가자",
                j: "pointer",
                K: "14px",
                k: "btn$q1_유연,신중,온화_5",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "7" },
              transit: {},
              order: 0,
            },
          ],
        },
        "3841804A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330142,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI671c1e65ccac4e9496f7764b36932778_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 48 },
            shape: { type: 1, w: 320, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "3841805A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330143,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "친구들과 여행 왔는데\n음식이 부족할 것 같다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3841806A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330144,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3841807A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330145,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI47f0ed087ae64e6f9df147118fc23a62_png",
                O: true,
                T: 0,
                Q: "부족하면 나중에 배달시켜 먹지 뭐.",
                j: "pointer",
                K: "14px",
                k: "btn$q2-2_유연",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3841808A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330146,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI4a885a53f4564aee94aaf9660e6e4b64_png",
                O: true,
                T: 0,
                Q: "애초에 부족하지 않게 많이 산다.",
                j: "pointer",
                K: "14px",
                k: "btn$q2-2_신중,온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "10" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3841922A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330148,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "어려운 결정을 내려야 할 때는?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3841923A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330149,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3841924A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330150,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIe26fdc0bb331437cb6aa435b844223a7_png",
                O: true,
                T: 0,
                Q: "망설이거나 다른사람에게 결정권을 준다.",
                j: "pointer",
                K: "14px",
                k: "btn$q2-3_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3841925A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330151,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIbee8e37796d1425c85d9e05d56edf430_png",
                O: true,
                T: 0,
                Q: "여러가지 방안을 고민해보고 받아들인다.",
                j: "pointer",
                K: "14px",
                k: "btn$q2-3_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3842067A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330153,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "어려운 결정을 내려야 할 때",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3842068A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330154,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3842069A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330155,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIe26fdc0bb331437cb6aa435b844223a7_png",
                O: true,
                T: 0,
                Q: "망설이거나 다른 사람한테 결정권을 준다",
                j: "pointer",
                K: "14px",
                k: "btn$q3_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "12" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|80",
              order: 1,
            },
          ],
        },
        "3842070A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330156,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIbee8e37796d1425c85d9e05d56edf430_png",
                O: true,
                T: 0,
                Q: "여러가지 방안을 고민해보고 받아들인다",
                j: "pointer",
                K: "14px",
                k: "btn$q3_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "12" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|80",
              order: 1,
            },
          ],
        },
        "3842234A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330158,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "친구들과 있을 때 말실수를 했다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3842235A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330159,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3842236A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330160,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIe26fdc0bb331437cb6aa435b844223a7_png",
                O: true,
                T: 0,
                Q: "하 난 도대체 왜이러지.",
                j: "pointer",
                K: "14px",
                k: "btn$q3-2_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "13" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3842237A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330161,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIbee8e37796d1425c85d9e05d56edf430_png",
                O: true,
                T: 0,
                Q: "괜찮아 긍정적으로 생각하자.",
                j: "pointer",
                K: "14px",
                k: "btn$q3-2_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "13" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3842343A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330163,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI2677831179d94da6b42ffebd55a99476_png",
                O: true,
                T: 0,
                Q: "신년 계획을 하나도 지키지 못했다면?",
                L: "#FFFFFF",
                K: "16px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 20, y: 251 },
            shape: { type: 1, w: 320, h: 75 },
            cx: 0,
            cy: 0,
          },
        },
        "3842344A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330164,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI6e12856a651a4570a7a7c76b480307a3_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 40, y: 224 },
            shape: { type: 1, w: 48, h: 49 },
            cx: 0,
            cy: 0,
          },
        },
        "3842345A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330165,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIe26fdc0bb331437cb6aa435b844223a7_png",
                O: true,
                T: 0,
                Q: "다음엔 할 수 있는 걸로 짜야겠다.",
                j: "pointer",
                K: "14px",
                k: "btn$q3-3_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 375 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3842346A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330166,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIbee8e37796d1425c85d9e05d56edf430_png",
                O: true,
                T: 0,
                Q: "나 자신을 받아들인다.",
                j: "pointer",
                K: "14px",
                k: "btn$q3-3_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 39, y: 451 },
            shape: { type: 1, w: 281, h: 55 },
            cx: 0,
            cy: 0,
          },
        },
        "3842676A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330185,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVa9cfe9cf072b4378877b34f5d1b1ffdc_mp4",
                k: "v$video_적극_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842677A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330186,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVbe8c185f1f114b7492873a5aa78b5cb9_mp4",
                k: "v$video_신중_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842678A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330187,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVe28be87995254ed7b891801a863a954b_mp4",
                k: "v$video_유연_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842679A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330188,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV03ee3dde26d24e6096e7ccd1148dce5d_mp4",
                k: "v$video_온화_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842680A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779788,
            zIndex: 101330189,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$ending" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "3842681A1_",
              "3842682A1_",
              "3842683A1_",
              "3842684A1_",
              "3842685A1_",
            ],
            layers: {
              1: { title: "명료", id: "3842681A1_" },
              2: { title: "온화", id: "3842682A1_" },
              3: { title: "유연", id: "3842683A1_" },
              4: { title: "신중", id: "3842684A1_" },
              5: { title: "적극", id: "3842685A1_" },
            },
            layerIndex: 5,
          },
        },
        "3842681A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330190 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3842686A1_", "3842687A1_"] },
        },
        "3842682A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330191 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3842679A1_", "3842688A1_"] },
        },
        "3842683A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330192 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3842678A1_", "3842689A1_"] },
        },
        "3842684A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330193 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3842677A1_", "3842690A1_"] },
        },
        "3842685A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330194 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3842676A1_", "3842691A1_"] },
        },
        "3842686A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330195,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV644e550fec144aa2bb0b7dfff641830d_mp4",
                k: "v$video_명료_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 802 },
            cx: 0,
            cy: 0,
          },
        },
        "3842687A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330196,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV302d563415174930b2f2fb0624a8a78a_mp4",
                k: "v$video_명료_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 802 },
            cx: 0,
            cy: 0,
          },
        },
        "3842688A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330197,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV9113349779da407fa72ceb946c6e9266_mp4",
                k: "v$video_온화_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842689A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330198,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV7cb8ad5c0edd454fa246c4a7f5ae1856_mp4",
                k: "v$video_유연_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842690A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330199,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV1ed8c076db8f4fa784195153c2a0e195_mp4",
                k: "v$video_신중_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3842691A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330200,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVf89607b6fc4442a285d109e42415a203_mp4",
                k: "v$video_적극_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: -1 },
            shape: { type: 1, w: 360, h: 801 },
            cx: 0,
            cy: 0,
          },
        },
        "3843145A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 99999965,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI062dd0cd9ae549709ea1214d1c5aa897_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 360, h: 800 },
            cx: 0,
            cy: 0,
          },
        },
        "3843318A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101330214,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$progress", c: false },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 96 },
            shape: { type: 1, w: 360, h: 60 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3843319A1_"],
            layers: { 1: { title: "Layer1", id: "3843319A1_" } },
            layerIndex: 1,
          },
        },
        "3843319A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330215 },
          init: {
            position: { x: 0, y: 96 },
            shape: { type: 1, w: 360, h: 60 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3843320A1_", "3843321A1_"] },
        },
        "3843320A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101330216,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, B: "#000000" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 16, y: 119 },
            shape: { type: 1, w: 320, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "3843321A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101330217,
            data: {
              properties: {
                attrs: {
                  HTML: '<progress id="progress" max="100" value="0"></progress>',
                },
              },
              wgtID: "ux.wgt.DIV",
              wgtTitle: "DIV <HTML>",
              styles: {},
              lockType: 0,
            },
          },
          init: {
            position: { x: 23, y: 123 },
            shape: { type: 1, w: 306, h: 12 },
            cx: 0,
            cy: 0,
          },
        },
        "3843484A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330219,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIba8dec4ee02e44de8d1a8d18b2bb87ed_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$reset",
                j: "pointer",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 279, y: 126 },
            shape: { type: 1, w: 40, h: 37 },
            cx: 0,
            cy: 0,
          },
        },
      },
      module: "apn.CFlowPage",
      BG: { fillStyle: "#ffffff" },
      SPT: {
        spt_EvtBubble:
          'if (!Event.target) {\r\n  if (Event.type == "Page Create") {\r\n    onPageCreate();\r\n  } else if (Event.type == "Page Run") {\r\n    onPageRun();\r\n  } else if (Event.type == "Custom Event") {\r\n    onCustomEvent();\r\n  }\r\n} else {\r\n  var label = Event.target.get("label");\r\n  if (Event.type == "Tap Start") {\r\n    if (label.indexOf("btn$q") > -1) {\r\n      onClickButton();\r\n    } else if (label == "i$reset") {\r\n      reset();\r\n    }\r\n  } else if (Event.type == "Media") {\r\n    if (Event.param == "End") {\r\n      if (label.indexOf("v$video_") > -1) {\r\n        onEndVideo();\r\n      }\r\n    }\r\n  }\r\n}\r\n\r\n// Page Craete\r\nfunction onPageCreate() {\r\n  onCustomProgressBar();\r\n  set("@charTimes", [2000, 3000, 3000, 2000, 3000]);\r\n}\r\n\r\n// Page Run\r\nfunction onPageRun() {\r\n  set("@types", {\r\n    명료: 0,\r\n    적극: 0,\r\n    유연: 0,\r\n    신중: 0,\r\n    온화: 0,\r\n  });\r\n//   $W("i$char_", undefined, { multiple: true, like: true }).forEach(function (\r\n//     char,\r\n//     index\r\n//   ) {\r\n//     char.blink(get("@charTimes")[index], {\r\n//       timing: "ease-in-out " + get("@charTimes")[index] + "ms",\r\n//     });\r\n//   });\r\n}\r\n\r\n// 답 선택\r\nfunction onClickButton() {\r\n  var label = Event.target.get("label");\r\n  var targetType = label.split("_")[1];\r\n  targetType.split(",").forEach(function (type) {\r\n    incrementKeyValue(type);\r\n  });\r\n  if (\r\n    label == "btn$q1-4_명료" ||\r\n    label == "btn$q1-4_적극" ||\r\n    label == "btn$q2-2_유연" ||\r\n    label == "btn$q2-3_신중" ||\r\n    label == "btn$q2-3_온화" ||\r\n    label == "btn$q3-3_신중" ||\r\n    label == "btn$q3-3_온화"\r\n  ) {\r\n    onComplete();\r\n  }\r\n}\r\n\r\n// 결과 도출\r\nfunction onComplete() {\r\n  var result = findMaxKey();\r\n  var ending = $W("mlc$ending");\r\n  $W("mlc$main").changeState("ending");\r\n  ending.changeState(result);\r\n  $W("v$video_" + result + "_1").changeState("Play");\r\n  $W("mlc$progress").set("visibility", "hidden");\r\n}\r\n\r\n// 비디오 끝난 뒤\r\nfunction onEndVideo() {\r\n  var split = Event.target.get("label").split("_");\r\n  if (split[2] == 1) {\r\n    Event.target.set("visibility", "hidden");\r\n    $W("v$video_" + split[1] + "_2").changeState("Play");\r\n  }\r\n}\r\n\r\n// 특정 키의 값을 +1 하는 함수\r\nfunction incrementKeyValue(key) {\r\n  var object = get("@types");\r\n  if (object && typeof object === "object" && object.hasOwnProperty(key)) {\r\n    object[key] += 1;\r\n  } else {\r\n    console.log("유효한 객체가 아니거나 해당 키는 객체에 존재하지 않습니다.");\r\n  }\r\n}\r\n\r\n// 객체에서 최대 값을 가지는 키를 찾는 함수\r\nfunction findMaxKey() {\r\n  var object = get("@types");\r\n  var maxKey = null;\r\n  var maxValue = -Infinity;\r\n  for (var key in object) {\r\n    if (object.hasOwnProperty(key)) {\r\n      if (object[key] > maxValue) {\r\n        maxValue = object[key];\r\n        maxKey = key;\r\n      }\r\n    }\r\n  }\r\n  return maxKey;\r\n}\r\n\r\n// 커스텀 이벤트\r\nfunction onCustomEvent() {\r\n  $W("mlc$progress").set("visibility", "visible");\r\n  var value = Event.param.split("|")[1];\r\n  var progress = document.getElementById("progress");\r\n  var nowValue = progress.value;\r\n  var additionalvalue = 0.5;\r\n  var id = setInterval(frame, 5);\r\n  function frame() {\r\n    if (progress.value < value) {\r\n      progress.value = progress.value + additionalvalue;\r\n    } else {\r\n      clearInterval(id);\r\n    }\r\n  }\r\n}\r\n\r\n// progressBar 디자인 변경\r\nfunction onCustomProgressBar() {\r\n  var css = `#progress {\r\n    appearance: none;\r\n    width : 100%;\r\n    height : 100%;\r\n    position : absolute;\r\n  }\r\n  #progress::-webkit-progress-bar {\r\n    background:#ffffff;\r\n    border-radius:0px;        \r\n  }\r\n  #progress::-webkit-progress-value {\r\n    border-radius:0px;\r\n    background: #000000;        \r\n  }\r\n  #totalProgress {\r\n    appearance: none;\r\n    width : 100%;\r\n  }\r\n  #totalProgress::-webkit-progress-bar {\r\n    background:#ffffff;\r\n    border-radius:0px;\r\n    border : none;\r\n  }\r\n  #totalProgress::-moz-progress-bar {\r\n    background:#ffffff;\r\n    border-radius:0px;\r\n    border : none;\r\n  }\r\n  #totalProgress::-webkit-progress-value {\r\n    border-radius:0px;\r\n    background: #000000;        \r\n  }\r\n  `;\r\n\r\n  var head = document.head || document.getElementsByTagName("head")[0];\r\n  var style = document.createElement("style");\r\n\r\n  head.appendChild(style);\r\n\r\n  style.type = "text/css";\r\n  if (style.styleSheet) {\r\n    // This is required for IE8 and below.\r\n    style.styleSheet.cssText = css;\r\n  } else {\r\n    style.appendChild(document.createTextNode(css));\r\n  }\r\n}\r\n\r\n/**\r\n * 위젯을 깜빡이게 함\r\n *\r\n * @param {int} delay 딜레이 (1/1000sec)\r\n * @param {object} param opacityTo param 객체   @nullable\r\n *\r\n */\r\nWidget.prototype.blink = function (delay, param) {\r\n  this.local.isBlink = !this.local.isBlink;\r\n  this.moveBy("", this.local.isBlink ? -50 : 50, param);\r\n  var wgt = this;\r\n  this.local.blinkTimeoutId = setTimeout(function () {\r\n    wgt.blink(delay, param);\r\n  }, delay);\r\n};\r\n\r\n/**\r\n * 위젯 깜빡임을 멈춤\r\n */\r\nWidget.prototype.stopBlink = function () {\r\n  if (this.local.blinkTimeoutId) {\r\n    clearTimeout(this.local.blinkTimeoutId);\r\n    this.local.blinkTimeoutId = undefined;\r\n  }\r\n\r\n  this.local.isBlink = undefined;\r\n  this.opacityTo(1);\r\n};\r\n',
      },
    },
    S: {
      UI: { title: "START", noEditable: true },
      objects: {},
      module: "apn.CFlowStartPage",
    },
    E: {
      UI: { title: "OUT", noEditable: true },
      objects: {},
      module: "apn.CFlowEndPage",
    },
    I: {
      UI: { title: "IN", noEditable: true },
      objects: {},
      module: "apn.CFlowInPage",
    },
    C: {
      UI: { title: "CLIENT", noEditable: true },
      objects: {},
      module: "apn.CFlow2ndStartPage",
    },
  },
  layouts: {
    1: {
      CTXT: { deviceID: "EDU", wgtLibID: "EDU", exeID: "standard" },
      property: {
        screenSize: { w: 360, h: 800 },
        styles: {
          normal: {
            fontStyle: "#000000",
            fontStrokeStyle: "#FFA500",
            fontStrokeWidth: 0,
            font: "EF_watermelonSalad",
            fontSize: "24px",
            textAlign: "center",
            textValign: "middle",
            fillStyle: "#FFFFFF",
            strokeStyle: "#7E7E7E",
            lineWidth: 1,
            lineDash: null,
            lineEnd: "square",
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            angle: 0,
            title: "",
            visibility: true,
            alpha: 1,
            dragX: false,
            dragY: false,
            dragInParent: false,
            dragContainParent: false,
            csr: "apn.auto",
            fontItalic: false,
            fontBold: false,
            fontUnderlined: false,
            ltrSp: 0,
            textWordWrap: true,
            lnSp: 0,
            text: "",
          },
        },
        properties: { exeScript: 2 },
        skinID: "Apple",
        themeID: "EDU",
        skinShow: 1,
        CExe: {
          layout: {
            layout: "W",
            padding: { left: 0, right: 0, top: 0, bottom: 0, ofl: "C" },
            style: { bgImgPtn: "stretch", bgImg: {}, bgClr: null },
          },
          enhcTxt: "Y",
          loading: {
            type: "",
            img: { type: "" },
            spinner: { type: "roller1", strokeClr: null },
          },
          event: { TS1: "", PE: "", SL: "" },
          inputSave: "",
          inputTextScroll: "",
          inputDisableTabOrder: "",
          lng: { ime: "" },
          edtOpts: { keepLabelOnCopy: "", useGroupProp: "" },
          pageOutline: {
            radius: [{ LT: 0, LB: 0, RT: 0, RB: 0 }],
            shadow: [{ x: 0, y: 0, spread: 0, color: null }],
          },
          scBar: {
            clrThumb: "#7f7f7f",
            clrThumbHover: "#7f7f7f",
            clrTrack: "#dddddd",
            cRdr: "50%",
            noCustom: "",
          },
          splash: { img: {}, bgClr: null, w: 40 },
          brTm: { frameClr: null },
          spt2impt: {
            js: [{ name: "", lnP: "", lnE: "" }],
            media: [{ key: "", cmt: "", md: {} }],
            mediaA: [{ key: "", cmt: "", md: {} }],
          },
          spt2preq: [{ json: { size: 0, data: "" } }],
          mdLD: { type: "" },
          vdStrictPlay: "",
          apCH: { acnt: 0, vcnt: 0 },
          mediaOnHidden: "",
          js: { fs: [{ js: { size: 0, data: "" }, v: "", c: "" }] },
          pubDateUpdate: "",
          pubFonts: [{ face: "", path: "" }],
          customPath: { core: "" },
          exFonts: [
            {
              title: "EF_watermelonSalad",
              face: "EF_watermelonSalad",
              ln: "ko",
              noBold: "Y",
              path: "https://cdn.jsdelivr.net/npm/@noonnu/ef-watermelon-salad@0.1.0/index.min.css",
              pathL:
                "https://cdn.jsdelivr.net/npm/@noonnu/ef-watermelon-salad@0.1.0/index.min.css",
              pathL2: "",
            },
          ],
          exFontsPub: "",
          sns: { ogI: "", ogT: "", ogD: "", srD: "" },
          prvMode: { urlPrm: "" },
          apxTdata: [
            {
              data: {
                st: [
                  { t: "Name", c: "", o: "", type: "text", w: 0, apxIndex: 1 },
                ],
                data: {
                  idx: 2,
                  st: {
                    1: {
                      t: "Name",
                      c: "",
                      o: "",
                      type: "text",
                      w: 0,
                      apxIndex: 1,
                    },
                  },
                  tbl: [{ 1: "" }],
                  maxCount: 0,
                  o: "",
                },
              },
              desc: "",
              id: "",
              type: "",
            },
          ],
          apxTdataF: [
            {
              id: " Duplicated1",
              type: "",
              desc: "",
              json: { size: 0, data: "" },
            },
          ],
          apxTdataDesc: "",
        },
      },
      pages: {},
    },
  },
  flow: { pages: { 1: { init: { position: { x: 0, y: 0 } } } } },
  index: { pageID: 2, layoutID: 2, rscID: 676954356 },
  rsc: {},
};
