window.apnExeFile = {
  CTXT: { layoutID: 1 },
  property: {
    ver: "1.0",
    denyCloneLocal: true,
    allowClearTimeout: true,
    denyWidgetStartEvent: true,
    denyInvisibleIntersect: true,
    fixBookStartProcess: true,
    allowImmediateContentLoad: true,
    fixBookPageLayout: true,
    fixOveralyRun: true,
    fix2SideBookCase1: true,
    fixWgtPut: true,
    fixScreenPadding: true,
    corpID: "",
    accountID: "",
    title: "실수 TEST",
    categoryId: "",
    type: "P",
    id: "3b6b783dfd5941e1978c4a47d3e6e927",
    createDate: "20240709152330",
  },
  pages: {
    1: {
      UI: { title: "Page 1", order: 1 },
      objects: {
        "3836265A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101313227,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$main" },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            layers: {
              1: { title: "home", id: "3836266A1_" },
              3: { title: "q1", id: "3836445A1_" },
              4: { title: "q1-2", id: "3836634A1_" },
              5: { title: "q1-3", id: "3836814A1_" },
              6: { title: "q1-4", id: "3836972A1_" },
              7: { title: "q2", id: "3837102A1_" },
              8: { title: "q2(same)", id: "3837224A1_" },
              9: { title: "q2-2", id: "3837372A1_" },
              10: { title: "q2-3", id: "3837556A1_" },
              11: { title: "q3", id: "3837722A1_" },
              12: { title: "q3-2", id: "3837882A1_" },
              13: { title: "q3-3", id: "3838004A1_" },
              14: { title: "ending", id: "3838269A1_" },
            },
            layerIndex: 14,
            children: [
              "3836266A1_",
              "3836445A1_",
              "3836634A1_",
              "3836814A1_",
              "3836972A1_",
              "3837102A1_",
              "3837224A1_",
              "3837372A1_",
              "3837556A1_",
              "3837722A1_",
              "3837882A1_",
              "3838004A1_",
              "3838269A1_",
            ],
          },
        },
        "3836266A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313228 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "3836292A1_",
              "3836293A1_",
              "3836377A1_",
              "3836388A1_",
              "3836389A1_",
              "3836391A1_",
              "3836392A1_",
            ],
          },
        },
        "3836292A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313230,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIf03a340dbc8b4e618744ae31d4cebbca_png",
                C: 0,
                A: "transparent",
                a: false,
                j: "pointer",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 786, y: 705 },
            shape: { type: 1, w: 348, h: 91 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "3" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|25",
              order: 1,
            },
          ],
        },
        "3836293A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313231,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIf31e5ac329c94e5cbffe2252f403f78f_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 461, y: 197 },
            shape: { type: 1, w: 997, h: 486 },
            cx: 0,
            cy: 0,
          },
        },
        "3836362A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 99999975,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIeaa4e3d0fe59469d9beb1562deb8069d_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3836377A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313234,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIcbcee0b1194940f4a13dc1d433f9d7bf_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_1",
              },
            },
          },
          init: {
            position: { x: 329, y: 110 },
            shape: { type: 1, w: 198, h: 177 },
            cx: 0,
            cy: 0,
          },
        },
        "3836388A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313235,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI0406078c271f48eda5eb2b1f676802e3_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_5",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 381, y: 674 },
            shape: { type: 1, w: 203, h: 197 },
            cx: 0,
            cy: 0,
          },
        },
        "3836389A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313236,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI5eb8eef334bf4474b7f9abf23842bdfe_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1354, y: 175 },
            shape: { type: 1, w: 174, h: 172 },
            cx: 0,
            cy: 0,
          },
        },
        "3836391A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313237,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI51b618af49ca4cd5be424b3302235b78_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_3",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1487, y: 368 },
            shape: { type: 1, w: 192, h: 264 },
            cx: 0,
            cy: 0,
          },
        },
        "3836392A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313238,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIf4be53579c6c49e7b99f900387a28aef_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$char_4",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1237, y: 730 },
            shape: { type: 1, w: 190, h: 154 },
            cx: 0,
            cy: 0,
          },
        },
        "3836445A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313239 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3836461A1_", "3836496A1_", "3836514A1_", "3836515A1_"],
          },
        },
        "3836461A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313241,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "음식점에서 주문한 음식과 다른 음식이 나왔다면?",
                L: "#FFFFFF",
                K: "30px",
              },
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3836496A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313243,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3836514A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313248,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI5cbe6235f8c441cb86a87826e7a2c496_png",
                O: true,
                T: 0,
                Q: "바로 직원을 부른다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1_명료,적극",
              },
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "4" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|50",
              order: 1,
            },
          ],
        },
        "3836515A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313249,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI9fdb80c972504526ab00a9b76b214494_png",
                O: true,
                T: 0,
                Q: "주문서를 다시 확인해본다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1_유연,신중,온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "7" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|50",
              order: 1,
            },
          ],
        },
        "3836634A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313251 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3836755A1_", "3836757A1_", "3836758A1_", "3839993A1_"],
          },
        },
        "3836755A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313252,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "만약 업무 중에 실수로 중요한 문서를 삭제했다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3836757A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313254,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI5cbe6235f8c441cb86a87826e7a2c496_png",
                O: true,
                T: 0,
                Q: "백업된 파일이 있는지 바로 찾아본다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1-2_명료",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "5" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|75",
              order: 1,
            },
          ],
        },
        "3836758A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313255,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI9fdb80c972504526ab00a9b76b214494_png",
                O: true,
                T: 0,
                Q: "일단 충격받고 도움을 청한다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1-2_적극",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "5" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|75",
              order: 1,
            },
          ],
        },
        "3836814A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313257 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3836885A1_", "3836887A1_", "3836888A1_", "3840016A1_"],
          },
        },
        "3836885A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313258,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "내가 중요한 팀플에서 늦었다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3836887A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313260,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI5cbe6235f8c441cb86a87826e7a2c496_png",
                O: true,
                T: 0,
                Q: "왜 늦었는지 설명한다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1-3_명료",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "6" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3836888A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313261,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI9fdb80c972504526ab00a9b76b214494_png",
                O: true,
                T: 0,
                Q: "미안해ㅜㅜㅜ잘못했어ㅜㅜ흑흐규ㅠㅡㅠ",
                j: "pointer",
                K: "27px",
                k: "btn$q1-3_적극",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "6" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3836972A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313263 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837043A1_", "3837045A1_", "3837046A1_", "3840047A1_"],
          },
        },
        "3837043A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313264,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "교수님께 이메일을 잘못 보냈다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837045A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313266,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI5cbe6235f8c441cb86a87826e7a2c496_png",
                O: true,
                T: 0,
                Q: "처음부터 잘못보낼 일이 없다고 생각한다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1-4_명료",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837046A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313267,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI9fdb80c972504526ab00a9b76b214494_png",
                O: true,
                T: 0,
                Q: "빠르게 이메일을 즉시 회수한 후 \n오해를 방지하기 위해 다시 문자를 보낸다.",
                j: "pointer",
                K: "27px",
                k: "btn$q1-4_적극",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837102A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313269 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837165A1_", "3837167A1_", "3837168A1_", "3840062A1_"],
          },
        },
        "3837165A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313270,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "정말 착한 후배인데 실수를 많이 한다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837167A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313272,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI495500e2f577476c813a57ec904ffc49_png",
                O: true,
                T: 0,
                Q: "자꾸 실수하는데 착한 건 중요한 게 아니지",
                j: "pointer",
                K: "27px",
                k: "btn$q2_유연",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "9" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|75",
              order: 1,
            },
          ],
        },
        "3837168A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313273,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI3e03bf096b7a47208f3c73065f674094_png",
                O: true,
                T: 0,
                Q: "실수는 하지만 평소에 착하니까 넘어가자",
                j: "pointer",
                K: "27px",
                k: "btn$q2_신중,온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "11" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|60",
              order: 1,
            },
          ],
        },
        "3837224A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313275 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837287A1_", "3837289A1_", "3837290A1_", "3840077A1_"],
          },
        },
        "3837287A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313276,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "정말 착한 후배인데 실수를 많이 한다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837289A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313278,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RId39ece61072443a4958ff3ce5fe7555e_png",
                O: true,
                T: 0,
                Q: "자꾸 실수하는데 착한 건 중요한 게 아니지",
                j: "pointer",
                K: "27px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837290A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313279,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI7d55ba1035274496ac24a66b65bd33d9_png",
                O: true,
                T: 0,
                Q: "실수는 하지만 평소에 착하니까 넘어가자",
                j: "pointer",
                K: "27px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837372A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313281 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837461A1_", "3837463A1_", "3837464A1_", "3840092A1_"],
          },
        },
        "3837461A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313282,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "친구들과 여행 왔는데 음식이 부족할 것 같다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837463A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313284,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI495500e2f577476c813a57ec904ffc49_png",
                O: true,
                T: 0,
                Q: "부족하면 나중에 배달시켜 먹지 뭐.",
                j: "pointer",
                K: "27px",
                k: "btn$q2-2_유연",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837464A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313285,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI6dfaa5ff531a49e7a9ee94ddd0de835a_png",
                O: true,
                T: 0,
                Q: "애초에 부족하지 않게 많이 산다.",
                j: "pointer",
                K: "27px",
                k: "btn$q2-2_신중,온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "10" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3837556A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313287 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837627A1_", "3837629A1_", "3837630A1_", "3840107A1_"],
          },
        },
        "3837627A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313288,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "어려운 결정을 내려야 할 때는?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837629A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313290,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RId39ece61072443a4958ff3ce5fe7555e_png",
                O: true,
                T: 0,
                Q: "망설이거나 다른사람에게 결정권을 준다.",
                j: "pointer",
                K: "27px",
                k: "btn$q2-3_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837630A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313291,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI3e03bf096b7a47208f3c73065f674094_png",
                O: true,
                T: 0,
                Q: "여러가지 방안을 고민해보고 받아들인다.",
                j: "pointer",
                K: "27px",
                k: "btn$q2-3_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837722A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313293 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837823A1_", "3837825A1_", "3837826A1_", "3840122A1_"],
          },
        },
        "3837823A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313294,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "어려운 결정을 내려야 할 때",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837825A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313296,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RId39ece61072443a4958ff3ce5fe7555e_png",
                O: true,
                T: 0,
                Q: "망설이거나 다른 사람한테 결정권을 준다",
                j: "pointer",
                K: "27px",
                k: "btn$q3_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "12" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|80",
              order: 1,
            },
          ],
        },
        "3837826A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313297,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI3e03bf096b7a47208f3c73065f674094_png",
                O: true,
                T: 0,
                Q: "여러가지 방안을 고민해보고 받아들인다",
                j: "pointer",
                K: "27px",
                k: "btn$q3_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "12" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|80",
              order: 1,
            },
          ],
        },
        "3837882A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313299 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3837945A1_", "3837947A1_", "3837948A1_", "3840137A1_"],
          },
        },
        "3837945A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313300,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "친구들과 있을 때 말실수를 했다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3837947A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313302,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RId39ece61072443a4958ff3ce5fe7555e_png",
                O: true,
                T: 0,
                Q: "하 난 도대체 왜이러지.",
                j: "pointer",
                K: "27px",
                k: "btn$q3-2_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "13" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3837948A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313303,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI3e03bf096b7a47208f3c73065f674094_png",
                O: true,
                T: 0,
                Q: "괜찮아 긍정적으로 생각하자.",
                j: "pointer",
                K: "27px",
                k: "btn$q3-2_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWS",
              event: "tapStart",
              target: { pageID: "1", objectID: "3836265A1_", stateID: "13" },
              transit: {},
              order: 0,
            },
            {
              action: "FCE",
              event: "tapStart",
              param: "progress|100",
              order: 1,
            },
          ],
        },
        "3838004A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101313305 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["3838075A1_", "3838077A1_", "3838078A1_", "3840152A1_"],
          },
        },
        "3838075A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313306,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RIaa88e4e3fa7b44519c8a7cd89249c65d_png",
                O: true,
                T: 0,
                Q: "신년 계획을 하나도 지키지 못했다면?",
                L: "#FFFFFF",
                K: "30px",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 560, y: 295 },
            shape: { type: 1, w: 800, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3838077A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313308,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RId39ece61072443a4958ff3ce5fe7555e_png",
                O: true,
                T: 0,
                Q: "다음엔 할 수 있는 걸로 짜야겠다.",
                j: "pointer",
                K: "27px",
                k: "btn$q3-3_신중",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 522 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3838078A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101313309,
            data: {
              properties: { ver: 2, attrs: { apnPadding: "" } },
              wgtID: "apn.wgt.imageText",
              wgtTitle: "Image with Text",
              styles: {
                mediaID: "RI3e03bf096b7a47208f3c73065f674094_png",
                O: true,
                T: 0,
                Q: "나 자신을 받아들인다.",
                j: "pointer",
                K: "27px",
                k: "btn$q3-3_온화",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 643, y: 710 },
            shape: { type: 1, w: 634, h: 121 },
            cx: 0,
            cy: 0,
          },
        },
        "3838269A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330050 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3840465A1_", "3838274A1_", "3843379A1_"] },
        },
        "3838274A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101330051,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$ending" },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: {
            layers: {
              1: { title: "명료", id: "3838275A1_" },
              2: { title: "온화", id: "3838306A1_" },
              3: { title: "유연", id: "3838344A1_" },
              4: { title: "신중", id: "3838364A1_" },
              5: { title: "적극", id: "3838384A1_" },
            },
            layerIndex: 5,
            children: [
              "3838275A1_",
              "3838306A1_",
              "3838344A1_",
              "3838364A1_",
              "3838384A1_",
            ],
          },
        },
        "3838275A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330052 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3840442A1_", "3840441A1_", "3843442A1_"] },
        },
        "3838306A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330055 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3840568A1_", "3840530A1_", "3843458A1_"] },
        },
        "3838344A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330057 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3840628A1_", "3840608A1_", "3843473A1_"] },
        },
        "3838364A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330059 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3840660A1_", "3840650A1_", "3843488A1_"] },
        },
        "3838384A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330061 },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3840685A1_", "3840674A1_", "3843503A1_"] },
        },
        "3839993A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330089,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840016A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330090,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840047A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330091,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840062A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330092,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840077A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330093,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840092A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330094,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840107A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330095,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840122A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330096,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840137A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330097,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840152A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330098,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI890274e150d04de7b230d29162a70beb_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 543, y: 169 },
            shape: { type: 1, w: 176, h: 175 },
            cx: 0,
            cy: 0,
          },
        },
        "3840441A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330109,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVc180c37693bd45ccb3e672fb76b96e6b_mp4",
                k: "v$video_명료_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840442A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330108,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVff8d603172524bc395607efe0cf041df_mp4",
                k: "v$video_명료_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840465A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 99999973,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI2e189324425445abaf288ab9958abb20_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840530A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330110,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV18c9371276544faeb6b2c27f4b488cba_mp4",
                k: "v$video_온화_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840568A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 99999972,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV1fd90261d00f4df786570ffeac5bd574_mp4",
                k: "v$video_온화_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840608A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330112,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV0fe161bf6a5c4b47bb2f87f12f561d55_mp4",
                k: "v$video_유연_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840628A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 99999971,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV059786d14f9b43cda2bbe414c39d711a_mp4",
                k: "v$video_유연_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840650A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330114,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV16684dde6495442d9bee86db4531739a_mp4",
                k: "v$video_신중_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840660A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 99999970,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVa864787db8414224958d437cbb135da8_mp4",
                k: "v$video_신중_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840674A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 101330116,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RV3de567492c034c3dab8c7153c8b3ec32_mp4",
                k: "v$video_적극_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3840685A1_": {
          module: "apn.CVideo",
          create: {
            type: 16777728,
            zIndex: 99999969,
            data: {
              properties: {
                state: "stop",
                attrs: {
                  apxMediaControl: true,
                  Control: "None",
                  Loop: "No",
                  apxStep: { current: 0, count: 1 },
                  v: 2,
                  stp: 0,
                  ttip: "",
                  apxPoster: {},
                  apxAlpha: [
                    { clr: "Red", cnd: 0, v: 255 },
                    { clr: "Green", cnd: 0, v: 255 },
                    { clr: "Blue", cnd: 0, v: 255 },
                  ],
                  fs: {
                    oId: "",
                    lyI: "",
                    lyF: "",
                    subs: [{ oId: "", lng: "ko" }],
                  },
                },
              },
              wgtID: "apn.wgt.video",
              wgtTitle: "Video",
              styles: {
                mediaID: "RVf7d1de4a1bbf49fcac3e4404f28230fd_mp4",
                k: "v$video_적극_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1920, h: 1080 },
            cx: 0,
            cy: 0,
          },
        },
        "3843316A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101330210,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$progress", c: false },
            },
          },
          init: {
            position: { x: 182, y: 79 },
            shape: { type: 1, w: 1557, h: 61 },
            cx: 0,
            cy: 0,
          },
          layout: {
            layers: { 1: { title: "Layer1", id: "3843317A1_" } },
            layerIndex: 1,
            children: ["3843317A1_"],
          },
        },
        "3843317A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101330211 },
          init: {
            position: { x: 182, y: 79 },
            shape: { type: 1, w: 960, h: 720 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["3843341A1_", "3843342A1_"] },
        },
        "3843341A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101330212,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, B: "#000000" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 198, y: 102 },
            shape: { type: 1, w: 1525, h: 24 },
            cx: 0,
            cy: 0,
          },
        },
        "3843342A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101330213,
            data: {
              properties: {
                attrs: {
                  HTML: '<progress id="progress" max="100" value="0"></progress>',
                },
              },
              wgtID: "ux.wgt.DIV",
              wgtTitle: "DIV <HTML>",
              styles: {},
              lockType: 0,
            },
          },
          init: {
            position: { x: 205.5, y: 107 },
            shape: { type: 1, w: 1510, h: 14 },
            cx: 0,
            cy: 0,
          },
        },
        "3843379A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330215,
            data: {
              properties: { attrs: { cfg: { mr: "0" } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIe748b9cd58a24e1083727d94e70649e8_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$reset",
                j: "pointer",
              },
            },
          },
          init: {
            position: { x: 1738, y: 100 },
            shape: { type: 1, w: 75.27272727272748, h: 69 },
            cx: 0,
            cy: 0,
          },
        },
        "3843442A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330216,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI85d3de8b74134ac39bea8d4d845a9f12_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 610, y: 90 },
            shape: { type: 1, w: 699, h: 900 },
            cx: 0,
            cy: 0,
          },
        },
        "3843458A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330217,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RId33dcf098cb74b07a0077e4f72d5aaaa_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 610, y: 90 },
            shape: { type: 1, w: 699, h: 900 },
            cx: 0,
            cy: 0,
          },
        },
        "3843473A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330218,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIe2a3f49d12c7473faf1eafb27b95ba62_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 610, y: 90 },
            shape: { type: 1, w: 699, h: 900 },
            cx: 0,
            cy: 0,
          },
        },
        "3843488A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330219,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI85ebd8f9062048958dac8c0828100cac_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 610, y: 90 },
            shape: { type: 1, w: 699, h: 900 },
            cx: 0,
            cy: 0,
          },
        },
        "3843503A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101330220,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI01aca69ed1c141cca8badb0ab1cf9cea_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 610, y: 90 },
            shape: { type: 1, w: 699, h: 900 },
            cx: 0,
            cy: 0,
          },
        },
      },
      module: "apn.CFlowPage",
      BG: { fillStyle: "#ffffff" },
      SPT: {
        spt_EvtBubble:
          'if (!Event.target) {\r\n  if (Event.type == "Page Create") {\r\n    onPageCreate();\r\n  } else if (Event.type == "Page Run") {\r\n    onPageRun();\r\n  } else if (Event.type == "Custom Event") {\r\n    onCustomEvent();\r\n  }\r\n} else {\r\n  var label = Event.target.get("label");\r\n  if (Event.type == "Tap Start") {\r\n    if (label.indexOf("btn$q") > -1) {\r\n      onClickButton();\r\n    } else if(label == "i$reset") {\r\n      reset();\r\n    }\r\n  } else if (Event.type == "Media") {\r\n    if (Event.param == "End") {\r\n      if (label.indexOf("v$video_") > -1) {\r\n        onEndVideo();\r\n      }\r\n    }\r\n  }\r\n}\r\n\r\n// Page Craete\r\nfunction onPageCreate() {\r\n  onCustomProgressBar();\r\n  set("@charTimes", [2000, 3000, 3000, 2000, 3000]);\r\n}\r\n\r\n// Page Run\r\nfunction onPageRun() {\r\n  set("@types", {\r\n    명료: 0,\r\n    적극: 0,\r\n    유연: 0,\r\n    신중: 0,\r\n    온화: 0,\r\n  });\r\n  $W("i$char_", undefined, { multiple: true, like: true }).forEach(function (\r\n    char,\r\n    index\r\n  ) {\r\n    char.blink(get("@charTimes")[index], {\r\n      timing: "ease-in-out " + get("@charTimes")[index] + "ms",\r\n    });\r\n  });\r\n}\r\n\r\n// 답 선택\r\nfunction onClickButton() {\r\n  var label = Event.target.get("label");\r\n  var targetType = label.split("_")[1];\r\n  targetType.split(",").forEach(function (type) {\r\n    incrementKeyValue(type);\r\n  });\r\n  if (\r\n    label == "btn$q1-4_명료" ||\r\n    label == "btn$q1-4_적극" ||\r\n    label == "btn$q2-2_유연" ||\r\n    label == "btn$q2-3_신중" ||\r\n    label == "btn$q2-3_온화" ||\r\n    label == "btn$q3-3_신중" ||\r\n    label == "btn$q3-3_온화"\r\n  ) {\r\n    onComplete();\r\n  }\r\n}\r\n\r\n// 결과 도출\r\nfunction onComplete() {\r\n  var result = findMaxKey();\r\n  var ending = $W("mlc$ending");\r\n  $W("mlc$main").changeState("ending");\r\n  ending.changeState(result);\r\n  //$W("v$video_" + result + "_1").changeState("Play");\r\n  $W("mlc$progress").set("visibility", "hidden");\r\n}\r\n\r\n// 비디오 끝난 뒤\r\nfunction onEndVideo() {\r\n  var split = Event.target.get("label").split("_");\r\n  if (split[2] == 1) {\r\n    Event.target.set("visibility", "hidden");\r\n    $W("v$video_" + split[1] + "_2").changeState("Play");\r\n  }\r\n}\r\n\r\n// 특정 키의 값을 +1 하는 함수\r\nfunction incrementKeyValue(key) {\r\n  var object = get("@types");\r\n  if (object && typeof object === "object" && object.hasOwnProperty(key)) {\r\n    object[key] += 1;\r\n  } else {\r\n    console.log("유효한 객체가 아니거나 해당 키는 객체에 존재하지 않습니다.");\r\n  }\r\n}\r\n\r\n// 객체에서 최대 값을 가지는 키를 찾는 함수\r\nfunction findMaxKey() {\r\n  var object = get("@types");\r\n  var maxKey = null;\r\n  var maxValue = -Infinity;\r\n  for (var key in object) {\r\n    if (object.hasOwnProperty(key)) {\r\n      if (object[key] > maxValue) {\r\n        maxValue = object[key];\r\n        maxKey = key;\r\n      }\r\n    }\r\n  }\r\n  return maxKey;\r\n}\r\n\r\n// 커스텀 이벤트\r\nfunction onCustomEvent() {\r\n  $W("mlc$progress").set("visibility", "visible");\r\n  var value = Event.param.split("|")[1];\r\n  var progress = document.getElementById("progress");\r\n  var nowValue = progress.value;\r\n  var additionalvalue = 1;\r\n  var id = setInterval(frame, 5);\r\n  function frame() {\r\n    if (progress.value < value) {\r\n      progress.value = progress.value + additionalvalue;\r\n    } else {\r\n      clearInterval(id);\r\n    }\r\n  }\r\n}\r\n\r\n// progressBar 디자인 변경\r\nfunction onCustomProgressBar() {\r\n  var css = `#progress {\r\n    appearance: none;\r\n    width : 100%;\r\n    height : 100%;\r\n    position : absolute;\r\n  }\r\n  #progress::-webkit-progress-bar {\r\n    background:#ffffff;\r\n    border-radius:0px;        \r\n  }\r\n  #progress::-webkit-progress-value {\r\n    border-radius:0px;\r\n    background: #000000;        \r\n  }\r\n  #totalProgress {\r\n    appearance: none;\r\n    width : 100%;\r\n  }\r\n  #totalProgress::-webkit-progress-bar {\r\n    background:#ffffff;\r\n    border-radius:0px;\r\n    border : none;\r\n  }\r\n  #totalProgress::-moz-progress-bar {\r\n    background:#ffffff;\r\n    border-radius:0px;\r\n    border : none;\r\n  }\r\n  #totalProgress::-webkit-progress-value {\r\n    border-radius:0px;\r\n    background: #000000;        \r\n  }\r\n  `;\r\n\r\n  var head = document.head || document.getElementsByTagName("head")[0];\r\n  var style = document.createElement("style");\r\n\r\n  head.appendChild(style);\r\n\r\n  style.type = "text/css";\r\n  if (style.styleSheet) {\r\n    // This is required for IE8 and below.\r\n    style.styleSheet.cssText = css;\r\n  } else {\r\n    style.appendChild(document.createTextNode(css));\r\n  }\r\n}\r\n\r\n/**\r\n * 위젯을 깜빡이게 함\r\n *\r\n * @param {int} delay 딜레이 (1/1000sec)\r\n * @param {object} param opacityTo param 객체   @nullable\r\n *\r\n */\r\nWidget.prototype.blink = function (delay, param) {\r\n  this.local.isBlink = !this.local.isBlink;\r\n  this.moveBy("", this.local.isBlink ? -50 : 50, param);\r\n  var wgt = this;\r\n  this.local.blinkTimeoutId = setTimeout(function () {\r\n    wgt.blink(delay, param);\r\n  }, delay);\r\n};\r\n\r\n/**\r\n * 위젯 깜빡임을 멈춤\r\n */\r\nWidget.prototype.stopBlink = function () {\r\n  if (this.local.blinkTimeoutId) {\r\n    clearTimeout(this.local.blinkTimeoutId);\r\n    this.local.blinkTimeoutId = undefined;\r\n  }\r\n\r\n  this.local.isBlink = undefined;\r\n  this.opacityTo(1);\r\n};\r\n',
      },
    },
    S: {
      UI: { title: "START", noEditable: true },
      objects: {},
      module: "apn.CFlowStartPage",
    },
    E: {
      UI: { title: "OUT", noEditable: true },
      objects: {},
      module: "apn.CFlowEndPage",
    },
    I: {
      UI: { title: "IN", noEditable: true },
      objects: {},
      module: "apn.CFlowInPage",
    },
    C: {
      UI: { title: "CLIENT", noEditable: true },
      objects: {},
      module: "apn.CFlow2ndStartPage",
    },
  },
  layouts: {
    1: {
      CTXT: { deviceID: "EDU", wgtLibID: "EDU", exeID: "standard" },
      property: {
        screenSize: { w: 1920, h: 1080 },
        styles: {
          normal: {
            fontStyle: "#000000",
            fontStrokeStyle: "#FFA500",
            fontStrokeWidth: 0,
            font: "EF_watermelonSalad",
            fontSize: "24px",
            textAlign: "center",
            textValign: "middle",
            fillStyle: "#FFFFFF",
            strokeStyle: "#7E7E7E",
            lineWidth: 1,
            lineDash: null,
            lineEnd: "square",
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            angle: 0,
            title: "",
            visibility: true,
            alpha: 1,
            dragX: false,
            dragY: false,
            dragInParent: false,
            dragContainParent: false,
            csr: "apn.auto",
            fontItalic: false,
            fontBold: false,
            fontUnderlined: false,
            ltrSp: 0,
            textWordWrap: true,
            lnSp: 0,
            text: "",
            textMultiLine: false,
          },
        },
        properties: { exeScript: 2 },
        skinID: "Apple",
        themeID: "EDU",
        skinShow: 1,
        CExe: {
          layout: {
            layout: "W",
            padding: { left: 0, right: 0, top: 0, bottom: 0, ofl: "C" },
            style: { bgImgPtn: "stretch", bgImg: {}, bgClr: null },
          },
          enhcTxt: "Y",
          loading: {
            type: "",
            img: { type: "" },
            spinner: { type: "roller1", strokeClr: null },
          },
          event: { TS1: "", PE: "", SL: "" },
          inputSave: "",
          inputTextScroll: "",
          inputDisableTabOrder: "",
          lng: { ime: "" },
          edtOpts: { keepLabelOnCopy: "", useGroupProp: "" },
          pageOutline: {
            radius: [{ LT: 0, LB: 0, RT: 0, RB: 0 }],
            shadow: [{ x: 0, y: 0, spread: 0, color: null }],
          },
          scBar: {
            clrThumb: "#7f7f7f",
            clrThumbHover: "#7f7f7f",
            clrTrack: "#dddddd",
            cRdr: "50%",
            noCustom: "",
          },
          splash: { img: {}, bgClr: null, w: 40 },
          brTm: { frameClr: null },
          spt2impt: {
            js: [{ name: "", lnP: "", lnE: "" }],
            media: [{ key: "", cmt: "", md: {} }],
            mediaA: [{ key: "", cmt: "", md: {} }],
          },
          spt2preq: [{ json: { size: 0, data: "" } }],
          mdLD: { type: "" },
          vdStrictPlay: "",
          apCH: { acnt: 0, vcnt: 0 },
          mediaOnHidden: "",
          js: { fs: [{ js: { size: 0, data: "" }, v: "", c: "" }] },
          pubDateUpdate: "",
          pubFonts: [{ face: "", path: "" }],
          customPath: { core: "" },
          exFonts: [
            {
              title: "EF_watermelonSalad",
              face: "EF_watermelonSalad",
              ln: "ko",
              noBold: "Y",
              path: "https://cdn.jsdelivr.net/npm/@noonnu/ef-watermelon-salad@0.1.0/index.min.css",
              pathL:
                "https://cdn.jsdelivr.net/npm/@noonnu/ef-watermelon-salad@0.1.0/index.min.css",
              pathL2: "",
            },
          ],
          exFontsPub: "",
          sns: { ogI: "", ogT: "", ogD: "", srD: "" },
          prvMode: { urlPrm: "" },
          apxTdata: [
            {
              data: {
                st: [
                  { t: "Name", c: "", o: "", type: "text", w: 0, apxIndex: 1 },
                ],
                data: {
                  idx: 2,
                  st: {
                    1: {
                      t: "Name",
                      c: "",
                      o: "",
                      type: "text",
                      w: 0,
                      apxIndex: 1,
                    },
                  },
                  tbl: [{ 1: "" }],
                  maxCount: 0,
                  o: "",
                },
              },
              desc: "",
              id: "",
              type: "",
            },
          ],
          apxTdataF: [
            {
              id: " Duplicated1",
              type: "",
              desc: "",
              json: { size: 0, data: "" },
            },
          ],
          apxTdataDesc: "",
        },
      },
      pages: {},
    },
  },
  flow: { pages: { 1: { init: { position: { x: 0, y: 0 } } } } },
  index: { pageID: 2, layoutID: 2, rscID: 676954356 },
  rsc: {},
};
